config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def update
  end

  def delete
  end

  def show

  end

  def index
    @posts = Post.all
  end


private

  def post_params
    params.require(:post).permit(:title,:content)
  end

  def set_post
    @post = Post.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <meta name="U$ando bem $eu dinheiro" content="Conteúdo, dicas e exemplos para que suas ecolhas sejam melhores, impactando positivamente na sua vida financeira."/>
    <meta name="keywords" content="Finanças,Dicas,Dinheiro,Economia,Educação,Economizar"/>
    <meta name="author" content="Kaue Mateucci"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="fb:app_id" content="APPID"/>
    <meta property="og:title" content="U$ando bem $eu dinheiro" />
    <meta property="og:type" content="article"/>
    <meta property="og:description" content="Dicas do nosso dia a dia para melhorar suas escolhas, gerando impacto positivo em sua vida financeira." />
    <meta property="og:url" content="www.usandobemseudinheiro.com"/>
    <meta property="og:image" content= "https://usandobemseudinheiro.herokuapp.com/assets/emotionwapp-6e27522ec7bb60d50901b0dc4021838211adf57ead381fcff0c31556dd3956ac.jpg" />
    <title> U$ando bem seu $$ </title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    </body>
</html>

app/views/posts/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/posts/delete.html.erb
<h1>Post#delete</h1>
<p>Find me in app/views/post/delete.html.erb</p>

app/views/posts/index.html.erb
<div class="container">
  <h3> Há <%= @posts.count %> posts a sua disposição com assuntos do seu cotidiano para ajudar na sua vida financeira. </h3>
<!-- <%= link_to "Criar Post", new_post_path %> -->
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-6 col-sm-4">
        <%= link_to post_path(post) do%>
          <div class="card" >
            <h3> <%= post.title %> </h3>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h2> Digite o conteúdo do post: </h2>
  <%= form_for(@post) do |f| %>
    <div class="col-xs-3 col-sm-3">
      <div class="row">
        <div class="form-group">
          <%= f.label :Titulo %>
          <%= f.text_field :title, class: 'form-control' %>
          <%= f.label :Conteudo %>
          <%= f.text_area :content, class: 'form-control' %>
          <%= f.submit class: 'btn btn-primary',  value: 'Criar Post' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <%= link_to "Voltar a lista de todos os posts", posts_path %>
    <h3> Este post é sobre <%= @post.title %>: </h3>
  <div class="card-content">
    <p> <%= simple_format(@post.content) %> </p>
    <%= link_to "Voltar a lista de todos os posts", posts_path %>
    <br>
    <br>
    <br>
  </div>
</div>

app/views/posts/update.html.erb
<h1>Post#update</h1>
<p>Find me in app/views/post/update.html.erb</p>

app/views/shared/_footer.html.erb
<p class='footer'> All rights reserved © - U$ando bem $eu dinheiro </p>

app/views/shared/_navbar.html.erb
<div class='navbar_usando_bem'>
  <div class='hidden-xs'>
    <%= image_tag "emotionwapp.jpg", alt: "Kauê" , :class => "navbar-photo" %>
  </div>
  <h3 > U$ando bem $eu dinheiro </h3>
  <p> kauefm@gmail.com</p>
</div>